### ISSUE TITLE
make firmware - error

### ISSUE THREAD

**Issue by evildronepilot** [chevyhu/Flysky-OpenTX-Test-Branch#16]
I'm following the instruction from this website
https://github.com/chevyhu/Flysky-OpenTX-Test-Branch/wiki/Quick-start-guide-with-the-firmware

Make firmware
 command Returns an error would you mind posting BIN file please

**Comment by evildronepilot** [comment]
duplication.....

**Comment by jep4755** [comment]
HiI'm kinda lost with this update stuffanyway .could I get one file for DFUto update my radio .I already downloaded the SD card from there web site .Thanks Jim
    On Wednesday, February 13, 2019, 2:36:22 AM CST, evildronepilot <notifications@github.com> wrote:  
 
 
duplication.....
