### ISSUE TITLE
When putting in the USB to charge "Emergency Mode" flashes across the screen

### ISSUE THREAD

**Issue by FLDataTeK** [chevyhu/Flysky-OpenTX-Test-Branch#2]
As the title suggest. Here is a video showing the issue.  This is using Jimmy's compiled version firmware-nv14-120918-mode2-hall-jlucidar-46c9fd3.bin

https://youtu.be/r2fkthD_iwE

**Comment by chevyhu** [comment]
Hello, I have no this problem, please use the newest firmware, you can build the firmware yourself from the sourcecode here.

**Comment by chevyhu** [comment]
has been fixed
