### ISSUE TITLE
Problem with number on model name

### ISSUE THREAD

**Issue by twinjet75** [chevyhu/Flysky-OpenTX-Test-Branch#20]
Hi, I found a problem using number on model name. Number 5 is a space, does not appear word 5. If I press number 5 on the virtual keyboard and then other number (different from 5) space appear between caracther.

Other people have same issue?

BR

  Davide

**Comment by qba667** [comment]
@twinjet75, yes it is common bug, but I have fixed it in my repository. Changes will be merged as soon as I will get access to this one.

**Comment by arhifisyant** [comment]
you've merge your work qba667. So, means this case closed?

**Comment by discord5000** [comment]
This is fixed.
