### ISSUE TITLE
Logical switch value for RxBt not high enough

### ISSUE THREAD

**Issue by discord5000** [chevyhu/Flysky-OpenTX-Test-Branch#23]
I was attempting to set up an a<x logical switch for the flysky telemetry sensor RxBt and it can't go any higher than 2.50V. My brushless whoop vbat voltage comes through this sensor so maybe it needs to go much higher? At least 6V for 1S vbat and 5-6V receivers, maybe even same range as vbat/vfas if possible.

**Comment by arhifisyant** [comment]
Yes. please make this happen. at least set it 50V just to make a plenty room (like underground version, it is 300V if im not mistaken). I use RxBt also to monitor my airplane battery. 

*until now, I cheat the teemetry value so, I still got the RxBt warning alarm working. My battery is 3s(12,6V full, 11,1 nominal). I set a new telemetry data RxBC(stands for Receiver Battery custom), with offset -11.1V. Then create logical switch, whenever RxBC < 0, alarm triggered. But, But, But, But, I really want the logical switch value for RxBt is more than 50V. thank you. I hope somebody read this

**Comment by qba667** [comment]
Fixed by merging - moved to other repository - https://github.com/open-flysky
