### ISSUE TITLE
Input and Mixer Weight ranges

### ISSUE THREAD

**Issue by mavericm1** [chevyhu/Flysky-OpenTX-Test-Branch#3]
You are unable to use a weight of more than 100.  A weight of 200 is needed when trying to use RSSI on a channel so you can get the correct value represented in betaflight or other software

**Comment by jep4755** [comment]
HiI have the Flysky Nirvana NV14I have version 2.2.2  Data Version 218is this up to date ?Under radios they don't list it I down loaded the companion it doesn't have it listed either.If it's not up to date do you have a newfirmware file I can get?any help would be appreciatedThanks Jim  

NIRVANA (NV14)
    On Sunday, January 6, 2019, 12:06:16 PM CST, mavericm1 <notifications@github.com> wrote:  
 
 
You are unable to use a weight of more than 100. A weight of 200 is needed when trying to use RSSI on a channel so you can get the correct value represented in betaflight or other software

**Comment by mavericm1** [comment]
> HiI have the Flysky Nirvana NV14I have version 2.2.2  Data Version 218is this up to date ?Under radios they don't list it I down loaded the companion it doesn't have it listed either.If it's not up to date do you have a newfirmware file I can get?any help would be appreciatedThanks Jim   NIRVANA (NV14) On Sunday, January 6, 2019, 12:06:16 PM CST, mavericm1 <notifications@github.com> wrote: You are unable to use a weight of more than 100. A weight of 200 is needed when trying to use RSSI on a channel so you can get the correct value represented in betaflight or other software — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.  Please see this link and look for the section on updating  https://static1.squarespace.com/static/5bc852d6b9144934c40d499c/t/5c1a07ad2b6a284e2bed3312/1545209816623/Nirvana+20181127.pdf

This is the wrong place to ask this sort of question.  But at this time the NV14 isn't supported by the companion like a normal opentx radio is as its still being developed.  To update the firmware

**Comment by chevyhu** [comment]
@mavericm1  will fix it, thank you.

**Comment by chevyhu** [comment]
@jep4755 The companion not support NV14 by now, we update the firmware by DFU, for the firmware, I suggest you use the latest firmware in this place, but you need to compile it yourself. 
here is a link:https://github.com/chevyhu/Flysky-OpenTX-Test-Branch/wiki/Quick-start-guide-with-the-firmware

**Comment by chevyhu** [comment]
fixed on b5bb88022af5269699b7ebe83574f9351ac89ec2
