### ISSUE TITLE
A bug with spaces between texts

### ISSUE THREAD

**Issue by chinmaynsamant** [chevyhu/Flysky-OpenTX-Test-Branch#31]
This a very little cosmetic bug but it is present since the earliest of the firmwares. With this, you can't delete the text after the spaces. This only happens when the text is pre-loaded (for example, it was already present in the previous models before loading the new firmware).

Example in Model name: If the model name was ZOHD Dart in the pre-loaded model. And now you want to change it. You can only delete ZOHD part. Not matter what the curser doesn't move to Dart.

Example in new Widgets functionality: If you want to set a TEXT widget, the pre-loaded name is My Label. You can only delete My. You can't delete Label.

**Comment by qba667** [comment]
Merged from my other repository.
