### ISSUE TITLE
Button function of trim joysticks.

### ISSUE THREAD

**Issue by ch3at** [chevyhu/Flysky-OpenTX-Test-Branch#33]
You can press trim joystick, but you can't assign any reaction to this.

**Comment by chinmaynsamant** [comment]
Given that it is a button and also a basic joystick, we can use it to move the cursor. Sometimes it is very hard to use the touch function in the corners of the screen. The use of the trim buttons will be perfect in this case.

**Comment by qba667** [comment]
Used for LUA right now - maybe later we can use it for navigation as well.
