### ISSUE TITLE
"RX Still connected" does not allow a force shutdown of the TX

### ISSUE THREAD

**Issue by TimothyGold** [chevyhu/Flysky-OpenTX-Test-Branch#36]
In my X7 using OpenTX 2.2.3 I can force to override the "RX Still Connected" Warning, but in the NV14 I am unable to force a shutdown.  I just get the repeated warning and a continual buzz over and over again.

**Comment by TimothyGold** [comment]
Stefan in rcgroups did let us know that this can be disabled in the Radio Config page.  I do think having this enabled as a warning is still useful but being able to override it like we can in the QX7 would be useful.
https://www.rcgroups.com/forums/showthread.php?3023832-UndergroundFPV-Dark-Knight-Radio/page146#post41805271

**Comment by qba667** [comment]
@TimothyGold good point - warning should be there.

**Comment by qba667** [comment]
@TimothyGold  implemented as dialogue that allows to turn off device after shutdown sequence. Please verify using updater I posted in other issue.
