### ISSUE TITLE
Overlaying menu items

### ISSUE THREAD

**Issue by eshifri** [chevyhu/Flysky-OpenTX-Test-Branch#39]
In the file ./gui/480x272/radio_version.cpp
the following buttons are drawn on the same place (window->height() - 100):

 new TextButton(window, {LCD_W/2-125, window->height() - 100, 250, 30}, STR_USER_MANUAL, [=]() -> int8_t {
      new QR_CodeMenu(QR_CODE_USER_MANUAL);
      return 1;
  });
  new TextButton(window, {LCD_W/2-125, window->height() - 100, 250, 30}, STR_FACTORYRESET, [=]() -> int8_t {
    auto dialog = new Dialog(WARNING_TYPE_INPUT, STR_CONFIRMRESET, STR_STORAGE_FORMAT, [=]() {
      storageEraseAll(false);
      NVIC_SystemReset();
      return 0;
    });

**Comment by qba667** [comment]
Fixed in open-flysky/Flysky-OpenTX-Test-Branch
