### ISSUE TITLE
NV14 External Trainer Port not deployed

### ISSUE THREAD

**Issue by TimothyGold** [chevyhu/Flysky-OpenTX-Test-Branch#43]
Just adding to the list of things that I discover that I use in my other radios that are needed in my NV14 to be useful at all.  I use the Trainer port for Head Tracking on my UAVs and I noticed that the trainer drivers are there in the target folders for NV14 but not deployed and if0 out.  I know this will be a huge challenge considering all the unique differences in Hardware from Taranis, Horus, etc.  I wish I could help on this but its way above my head.  Thanks again for helping make this radio work.

**Comment by qba667** [comment]
@TimothyGold following your change a did the hard part. Please get it from https://github.com/open-flysky/NV14-updater/releases and verify.
