### ISSUE TITLE
Auto switch selection does not work for LS and SF

### ISSUE THREAD

**Issue by eshifri** [chevyhu/Flysky-OpenTX-Test-Branch#44]
Newly implemented Auto Switch Selection option (in open-FlySky fork) does not work for logical switches (and switch) and special functions. (Works on all other screens.)

**Comment by qba667** [comment]
@eshifri thanks for testing! Probably other controls are used there. Let me check, I will let you know as soon as I will resolve it.

**Comment by eshifri** [comment]
The code is calling the same SwitchChoice() function.
Actually, not only the and switch does not work - the auto select functionality does not work for any switch in this file (V1, V2 AND switch).
