### ISSUE TITLE
SD Card file management needs work - Model Delete only deletes Model index from list but files continue to build.

### ISSUE THREAD

**Issue by TimothyGold** [chevyhu/Flysky-OpenTX-Test-Branch#45]
File cleanup on SD card after deleting models etc. does not happen.  This can be very confusing when trying to backup models and restore models with the actual files in the Models folder.  Manual edit of the Model list with the right file name does seem to work but finding the right file that holds the correct model is not user friendly.

**Comment by kilrah** [comment]
That is intentional, so you can recover a model deleted by mistake. The filename for a given model is displayed on the model select screen.

**Comment by TimothyGold** [comment]
OK.  Thanks for letting me know.  I just noticed that it was different than the model delete used in Taranis where they do delete the file.  If I wanted to recover and restore a model I guess I would just have to edit the model list txt file with the correct file name... Is that correct?  Other than this I don't see a way to restore a model file...  No restore options....

**Comment by kilrah** [comment]
Correct.

**Comment by TimothyGold** [comment]
Thanks again for clarifying the intent.
