### ISSUE TITLE
Use github "Releases" for each compiled revision.

### ISSUE THREAD

**Issue by alvaroloes** [chevyhu/Flysky-OpenTX-Test-Branch#47]
Hi!

Would it be possible to generate a release for each compiled version of the firmware?
I found the latest release in a post in the RCGroups forum, which is hard to find.

Thanks!

**Comment by qba667** [comment]
@alvaroloes check this out https://github.com/open-flysky/NV14-updater/releases

**Comment by alvaroloes** [comment]
Thank you!
