### ISSUE TITLE
Not able to set 16ch output on R9M module. 

### ISSUE THREAD

**Issue by evildronepilot** [chevyhu/Flysky-OpenTX-Test-Branch#48]
Hi. I can only output 8 channel. Module is set to 16ch with dips witches,  channel range 1ch to 16ch output power 25mw receiver rebounded..... INAV and Beta flight are only seeing 8 bars moving.

**Comment by kilrah** [comment]
BF by default doesn't process all channels to save processing time, there's a CLI parameter to change of you want more.

**Comment by evildronepilot** [comment]
https://github.com/iNavFlight/inav/issues/4568
