### ISSUE TITLE
definitions mismatch

### ISSUE THREAD

**Issue by eshifri** [chevyhu/Flysky-OpenTX-Test-Branch#49]
DialogType enum values in dialog.h
enum DialogType {
  WARNING_TYPE_ALERT,
  WARNING_TYPE_ASTERISK,
  WARNING_TYPE_CONFIRM,
  WARNING_TYPE_INPUT,
  WARNING_TYPE_INFO
};
 do not match the corresponding #define(s) in gui.h:
#define WARNING_TYPE_ASTERISK          0
#define WARNING_TYPE_CONFIRM           1
#define WARNING_TYPE_INPUT             2

It does not create immediate problems, but the better way IMHO will be:
enum DialogType {
  WARNING_TYPE_ASTERISK,
  WARNING_TYPE_CONFIRM,
  WARNING_TYPE_INPUT,
  WARNING_TYPE_ALERT, 
  WARNING_TYPE_INFO
};

**Comment by qba667** [comment]
@eshifri  good point - it need to be cleaned up. Can we move to Flysky repository?
https://github.com/open-flysky/Flysky-OpenTX-Test-Branch

**Comment by eshifri** [comment]
Of course we can move wherever you say :-), but I'm not sure I understand how to do that: openTX/Flysky-OpenTX-Test-Branch does not allow issues reporting if this is what you mean.

**Comment by qba667** [comment]
@eshifri thanks for PR, unfortunately I have no rights to change other repository settings.
