### ISSUE TITLE
Altitude sensor FS-CAT01 and TGY-CAT01

### ISSUE THREAD

**Issue by CharlesGauci** [chevyhu/Flysky-OpenTX-Test-Branch#50]
Hi,

I had a conversation in Derdoktor667's Branch regarding Telemetry Sensors, 'Closed Issue number 9'. I have been trying to find the right settings for months but never had any luck.

I am trying different settings on the RATIO option to no avail, the altitude gives a negative measure. There must be something wrong in the Unit and Ratio keys in the Telemetry Edit screen.

Derdoktor667 and Eshifri tried to do some adjustments in line 273 so as the Ratio option can allow negative values but it did not work.

Eshifri found that the Altitude sensor is processed in telemetry_nv14.cpp and thinks that there is something wrong in the function 'CalculateAltitude()' in line 97 that has all constants hard-coded and was called from the line 173.

I asked about this issue in RC Groups  Report Number 1906 in March and would appreciate if you could give us some support in this issue.

I would like to take this opportunity to congratulate you and thank you for the great work that you have been doing in this project,

Charles

**Comment by CharlesGauci** [comment]
Below is a copy of the conversation that I had in Derdoktor667's Branch for your perusal



Hi,
I don't know if you can help me but I would appreciate if you do.

Can the 'Ratio' in the sensor edit list be changed to allow negative values, say '-1000'?

I use the altitude sensor fs-cat01. The air pressure reading in the Telemetry sensors is more or less correct. I created a copy with UNIT in meters (M).

I am trying different settings on the RATIO option to no avail, the altitude gives a negative measure.

I believe that the UNIT or the RATIO icon is the problem. Is there a way you can help me out with this issue? I asked about this in RC Groups months ago but I had no luck.

Once again I would like to thank you for the excellent work that you are doing, thanks also to Eshifri who is supporting you a lot.

 @eshifri
 
eshifri commented 3 days ago
Hi CharlesGauci,
I do not have this sensor, so I cannot try it, but if you need a negative RATIO value it is line 273 of model_telemetry.cpp:
new NumberEdit(sensorOneWindow, grid.getFieldSlot(), 0, 30000,
GET_SET_DEFAULT(sensor->custom.ratio));
so it might be sufficient to change 0 to -3000.
May be derdoktor667 can create a build for you to try.
I can do it on my branch but it is rather different from this one, so I would suggest against switching to it if you are happy with current performance in other aspects.

 @derdoktor667
 Owner
derdoktor667 commented 3 days ago • 
....one moment guys

...already compiling by remote ...please hold the line ;)

 @derdoktor667
 Owner
derdoktor667 commented 3 days ago • 
....here you are, Sir

firmware_telemetrix_test_060819_nv14.zip

...and by the way ...I push this, and it will be available in future builds.

....and thank you, eshifri ....and "you are very welcome, Sir" ;)

 @derdoktor667 derdoktor667 closed this 3 days ago
 @derdoktor667 derdoktor667 reopened this 3 days ago
@derdoktor667
 Owner
derdoktor667 commented 3 days ago
....yes / no / maybe??? ...closed ´till negatives

 @derdoktor667 derdoktor667 closed this 3 days ago
@CharlesGauci
 Author
CharlesGauci commented 3 days ago
Thanks a lot to both of you, will try it tomorrow as my wife is complaining to take her out for a drink :)

 @CharlesGauci
 Author
CharlesGauci commented 2 days ago
Good morning, installed it half an hour ago.

Ratio from default zero I press 'MIN' value becomes 62536. It looks like a plus number not minus.
Ratio from default zero I press '<<' value becomes 65526. Plus not minus.
Ratio from default zero I press '-' value becomes 65535 plus.
from '<< 65526' I pressed '-' value became 30,000 so I tried pressing '<<' several times which decreased by ten each time. when I reached zero (that is after 3000 times) the value came back to 65526 plus.

I cannot find a way to get a value in minus.

Sorry for the bad news,

Charles

 @eshifri
 
eshifri commented 2 days ago
Sorry, my bad: ratio is unsigned for every telemetry sensor.
It is more complicated than I hoped.

 @eshifri
 
eshifri commented 2 days ago
Looks like the only negative value supported is for OFFSET. And offset is used as a multiplier in the code.
It is also possible that this sensor is not supported yet.

 @CharlesGauci
 Author
CharlesGauci commented 2 days ago
Thank you for trying anyway. I do not think that the sensor is not supported yet at the air pressure right now is reading 1011.8 which is very close to the average atmospheric pressure of 1013.25.

I made a query in RC Groups on the 28th of March and QBA667 replied that he was going to use the algorithm that he did on the FS-I6, but this never happened. I wrote a reminder on the 13th of May but I am feeling shy to ask him again. Maybe one day he will implement it.

 @eshifri
 
eshifri commented 2 days ago • 
I have found Jakub's implementation for FS-i6: qba667/FlySkyI6@094ad2a
It is rather involved and requires significant telemetry signal processing.
I'm afraid your best bet is to wait for him to port it or ask him again.
Looks like changes to the formula parameters will not do it.

 @eshifri
 
eshifri commented 2 days ago • 
Kraus, sorry for converting your bug reports page into discussion forum. :-)

 @derdoktor667
 Owner
derdoktor667 commented 2 days ago
....no problem, guys ...short question: ...the negatives doesn´t work, right???

 @CharlesGauci
 Author
CharlesGauci commented 2 days ago
That's it, when I press the negative a value in plus comes in.

 @CharlesGauci
 Author
CharlesGauci commented 2 days ago
I am not feeling comfortable to ask Jakub for the third time, someone commented that I am creating a fuss about something when other more important topics still need to be done on this radio.

For me, being a thermal soarer, it is useless without an altitude sensor. 

 @derdoktor667
 Owner
derdoktor667 commented 2 days ago
...sorry for that ...I don´t have any telemetrics to work with it. I reverted yesterdays commit ...

 @CharlesGauci
 Author
CharlesGauci commented 2 days ago
So if I reinstall your current release should it delete yesterday's update? I can still leave it as it is as I will not be using the minus tabs anyway.


 @derdoktor667
 Owner
derdoktor667 commented 2 days ago
...today will be no release ...the one you installed is a custom version (compiled) ...today I just reverted the change eshifri suggested ...I think, keep it until next release (this weekend???)
...hmmm, I thought the Paladin will be an AFHDS3 radio ...will it be able to adapt an AFHDS2 receiver incl. telex???

 @CharlesGauci
 Author
CharlesGauci commented 2 days ago
Yesterday I asked Flysky in RC Groups 'New listing PL18 ' if they are compatible and still waiting for a reply. Probably it will need a separate rf module.

 @eshifri
 
eshifri commented 2 days ago
I have found that Altitude sensor is processed in telemetry_nv14.cpp and all constants are hard-coded there.

 @CharlesGauci
 Author
CharlesGauci commented 2 days ago
I think I found it, seems like those are for air pressure which is working fine. Could it be line 67 'Air Pressure Alt' Unit Meters which is giving opposite values?

I really appreciate your help

 @eshifri
 
eshifri commented yesterday
There is a function CalculateAltitude() at line 97 that has all constants hard-coded.
It is called from the line 173. Something is not correct around these areas.

 @CharlesGauci
 Author
CharlesGauci commented yesterday • 
Do you think, if there is a way, we should forward this conversation to qba667 maybe he can help us? I understand, Mr Wasl Kraus, being your Branch you decide on this.

 @derdoktor667
 Owner
derdoktor667 commented 23 hours ago
....sure ...why not ...it´s not "mine" ......it´s "ours" ;)

**Comment by qba667** [comment]
@CharlesGauci 
My implementation from I6 was far beyond that what is in NV1 right now - for short period of time I had somewhere test version that used my algorithm. I just need to find where it was and implement it in official branch.

**Comment by CharlesGauci** [comment]
Hi Jacub, has there been any development on the set up of this sensor to work properly on the NV14? The only alternative I found to get the right altitude and vario  sounds was by having to install a module to the TX, a flight controller and GPS which will be too expensive to install on all my gliders.

**Comment by CharlesGauci** [comment]
Hi Jacub, sensor is working fine after the update of the 2nd September. Thank you very much for your support.
