### ISSUE TITLE
Logical switch condition cannot use negative numbers

### ISSUE THREAD

**Issue by eshifri** [chevyhu/Flysky-OpenTX-Test-Branch#7]
When creating logical switch for a<x and a>x operations there is no way to use a negative number; the allowed range is 0 - 256.

**Comment by arhifisyant** [comment]
yes, the range is invalid. Also, when I try to put for example "a>x"  , "a" is SWA, "x" is 250, the logical switch did not work when i flip SWA. Please fix this

**Comment by eshifri** [comment]
Actually, I believe it can be fixed by changing the line 154 in model_logical_switches.cpp (radio/gui/480x272) to
v2Edit = new NumberEdit(logicalSwitchOneWindow, grid.getFieldSlot(), -MAX_LS_DELAY, MAX_LS_DELAY, GET_SET_DEFAULT(cs->v2));
I'm not sure about using MAX_LS_DELAY here; it would look more logical just to use -100, 100, but I do not quite understand this code.

**Comment by eshifri** [comment]
fixed in the current code
