### ISSUE TITLE
Logical switch values 

### ISSUE THREAD

**Issue by mavericm1** [chevyhu/Flysky-OpenTX-Test-Branch#8]
It appears when using logical switch values a>x and possibly others you are unable to use a negative value in the values like -20 for instance.  This prevents you from matching in the lower half of a channel range

**Comment by mavericm1** [comment]
example here in the v1 and v2 field you cannot put a negative value

![49686485_2530948840253336_8045807130889945088_n](https://user-images.githubusercontent.com/33595410/50943018-fceaf180-1447-11e9-95a3-5177b429b424.jpg)

**Comment by arhifisyant** [comment]
this case is the same with case #7 , please fix this.

**Comment by mavericm1** [comment]
This is already open under issue #7  closing
