### ISSUE TITLE
Switch warning does not work

### ISSUE THREAD

**Issue by eshifri** [chevyhu/Flysky-OpenTX-Test-Branch#9]
When the Tx (NV14) is turned on with switches in non-default positions the warnings are not played although they are enabled in the model setup.
The throttle warning works.

**Comment by eshifri** [comment]
OK, I have found that this functionality is deliberately disabled due to incomplete implementation of the GUI.

**Comment by alvaroloes** [comment]
Is there any progress on this issue? Any workaround?
